---
- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade Packages
  become: yes
  apt:
    upgrade: yes

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Install Dependencies
  become: yes
  apt:
    name: ["nodejs", "npm", "python", "tar"]
    state: latest
    update_cache: yes

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# https://docs.ansible.com/ansible/2.4/copy_module.html
- name: Copy Backend Artifacts
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz
    mode: 0400
    
# https://docs.ansible.com/ansible/2.3/unarchive_module.html
- name: Unarchive Backend Artifacts
  unarchive:
    src: ~/artifact.tar.gz
    dest: ~/
    remote_src: True

- name: Start Application
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
